### PR TITLE
tox

### PR DESCRIPTION
**Pull request by steenzout**
- added tox
- ability to test against ansible 1.9.4 and 2.0.1.0
- added travis-ci.org integration

### CODE REVIEW

**Comment by dellis23** [comment]
Thanks for this!  I'm not sure I'll have the time to review it soon, as I already have a few PRs outstanding on this repo.  Would you consider being a maintainer of the project for some period of time (however long you feel comfortable)?  I don't use Ansible anymore, so it makes it a bit more difficult to robustly test.

**Comment by steenzout** [comment]
@dellis23 sure.
do you want to make a `ansible-tookit` org? or I just PR to this repo?
you can reach me at my github handle @saucelabs.com if you want to setup a call or chat.

I already had a few ideas on how to improve it and I was going to pursue them [here](https://github.com/saucelabs-ansible/toolkit) since I saw a comment somewhere where you claimed you couldn't support it anymore.

As an example, I went through the ansible code and found a way where you could use `ansible.cfg` and therefore deprecate the need to have `~/.atk`.

by the way, great work!

**Comment by dellis23** [comment]
Thanks!  I'll add you as a contributor on here so you can have access to merge PRs, close issues, etc.  Do you also have a pypi account?  I can look into giving you permissions to publish new versions on there as well.

**Comment by steenzout** [comment]
@dellis23 yes, I created one last week.
steenzout is my login.

I've setup travis-ci in the past to automatically upload new releases/tags into pypi (if they pass their tests) so I can do it for this repo as well.

**Comment by dellis23** [comment]
@steenzout I've added you as a maintainer on pypi.  Thanks for doing this!

**Pull request merged**
